#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value', 'firstName' : 'Jason', 'lastName' : 'Bull' }
r = requests.post(url, files=payload)

print r.status_code
print r.text


